### ISSUE TITLE
Update to 1.20.0

### ISSUE THREAD

**Issue by XCraftTM** [Zingabopp/MultiplayerExtensions.VoiceChat#9]
I Don't know if you are working on this Project anymore but could you try to update this. I Think this could be amazing if the Original Mod "MultiplayerExtensions" would work for the 1.20.0 with this.

**Comment by Zingabopp** [comment]
I'm not really, may come back to it someday. As it is, it shouldn't be used anyway since voice data can run through Beat Games' servers which they don't want.
